### ISSUE TITLE
Provide option to install and run via a Docker image

### ISSUE THREAD

**Issue by nealmcb** [electionscience/vote.electionscience.org#113]
[Docker](https://en.wikipedia.org/wiki/Docker_%28software%29) makes it very easy to install and deploy software, for demos or for production.  Provide a Dockerfile to support this mode of operation, along with signatures to allow the use of [Docker Notary](https://blog.docker.com/tag/docker-notary/), which makes this significantly more secure than pip install, or even apt-get.

**Comment by rupalkhilari** [comment]
Thanks for the suggestion @nealmcb. We shall look into it.

**Comment by nealmcb** [comment]
Thank you!
