### ISSUE TITLE
Why not a mobile app? 

### ISSUE THREAD

**Issue by jcklpe** [electionscience/vote.electionscience.org#120]
Been a big fan of electology as a website and alternative forms of voting for awhile. I've found it odd that there aren't more voting mobile apps. This seems like it's a great place to start getting the idea out there with a simple interface that is friendly and well designed. Anyone interested in that?

**Comment by rupalkhilari** [comment]
Hi @thedonquixotic, that sounds like a good idea. Although making sure it would across android, iOS and windows would require more development. The current approval_frame app uses bootstrap and should be accessible from the phone browser as well. So I'm not so sure of it at the moment, but perhaps keep it as a lower priority would work ? Surely something that Aaron should decide about, we could take the discussion to the forum. 
Thanks!
