### ISSUE TITLE
Prompt before deleting choices

### ISSUE THREAD

**Issue by rupalkhilari** [electionscience/vote.electionscience.org#134]
On hitting the delete button for a choice, it would be nice to show a confirmation dialog box to check if the user really wanted to delete the choice before deleting it permanently.

**Comment by Faxn** [comment]
Deleting a choice isn't really that destructive. It's normally only going to be at most a sentence of text and if it's even possible to delete a choice, then the poll must have no votes in it. On top of that, deleting a choice in the edit page doesn't change the database, it's not until the form is submitted that anything is really changed. A conformation popup would probably be more of an annoyance than a enhancement.

If you really think we need something like this, I would recommend an alert that shows up at the top of the form and has a button to undo the deletion.  It would be harder to implement, but it provides the same oops protection while being less invasive. I could make it if you think the app needs something like that.

**Comment by rupalkhilari** [comment]
I agree with you @Faxn. Now that we have prevented choices from being edited if the poll has ballots on it, we might actually not need this. I like your idea of having the undo button instead though.
