### ISSUE TITLE
Choice links while editing polls

### ISSUE THREAD

**Issue by balajisubr** [electionscience/vote.electionscience.org#135]
* Go to edit page of a poll which has a link previously associated with a choice(say A)
* Change some thing else in the poll and click save
* Reload the poll. The link in choice A is not present anymore

**Comment by rupalkhilari** [comment]
@balajisubr, Did you enter a link in the link field for the choice and hit the 'Insert link' button ? It seems to be working on both the test server and locally for me. 
Are you referring to a case where the user enters a link as the choice text instead of inserting a link ? 
Let me know how you are testing this. 
Thanks!

**Comment by balajisubr** [comment]
@rupalkhilari The edit scenario is not working as explained above.

**Comment by balajisubr** [comment]
@rupalkhilari Couple questions regarding edit functionality for links:
1. Should existing choices be able to have their links added / modified / removed in the Edit page?
2. I currently observe while creating a new poll that adding a link to a choice successfully changes the link icon to a green color and that the link is not able to be modified? I was planning on removing the inability to modify it and extend the same functionality to the edit page. What do you think ?

**Comment by balajisubr** [comment]
@rupalkhilari Wondering if you have answers for the above questions? Should Aaron be involved? - Thanks

**Comment by rupalkhilari** [comment]
@balajisubr
1. If the poll already has ballots on it, I think we should not allow the links for choices to be modified. (There could be an edge case where the link expires and needs to be edited - but I think that is not a frequent occurrence)
2.  Great observation! The links should indeed be modifiable on the new poll page until the 'Create Poll' button is clicked. 

Thanks!
