### ISSUE TITLE
Add more info to messages shared to social media

### ISSUE THREAD

**Issue by rupalkhilari** [electionscience/vote.electionscience.org#143]
In the current state of the app, the social share buttons for a poll only share a link to the poll.

According to a discussion with Aaron, we need to customize these shared messages to add the CES logo, the question of the poll, along with the link.

**Comment by madhurimurali91** [comment]
@rupalkhilari Hi Rupal, I am working on this feature but I was wondering if there was a way to add logos to a tweet or facebook share. As far as I know, we can't do it unless it's an actual image upload. And doesn't facebook auto-generate images(possibly the logo) from the the given URL ?

**Comment by rupalkhilari** [comment]
@madhurimurali91 , As far as I know, Facebook uses the `<meta>` tag properties of the webpage to gather information about the shared message. Check more info [here](https://developers.facebook.com/docs/plugins/share-button#configurator)

For the image, you could probably use the logo that the app uses for the meta image https://github.com/electology/approval_frame/blob/master/approval_polls/static/approval_polls/images/logo-small.png if possible. 
One point to note is that Facebook considers pre-populating the message content of a post as a violation of their policy. More information [here](https://developers.facebook.com/docs/apps/review/prefill). However, Twitter does allow this.
