### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by rupalkhilari** [electionscience/vote.electionscience.org#148]
We need to figure out the account to be used for this, will depend on recommendations by Aaron

**Comment by balajisubr** [comment]
@rupalkhilari What are the capabilities / benefits of using Google Analytics?

**Comment by rupalkhilari** [comment]
@balajisubr , It would be to purely gather insights about the app usage, available to the admin. It could help collect data over time and answer some interesting questions like:  How often the site is accessed, how many requests per day/month/year, number of requests by region, percentage of requests from computer vs mobile devices. 
https://www.google.com/analytics/analytics/capabilities/
