### ISSUE TITLE
Polls in iframes on cross-domain pages fail CSRF check when 3rd-party cookies are blocked

### ISSUE THREAD

**Issue by kyleneideck** [electionscience/vote.electionscience.org#17]
This Django bug outlines the issue fairly thoroughly: https://code.djangoproject.com/ticket/17157. In short, when you create a poll and put the embedding code it provides (`<iframe src="http://localhost:8000/approval_polls/2" width="250"></iframe>`) on a page on another domain, browsers that disallow third party cookies can't vote. They see a Django 403 page with the message "CSRF verification failed. Request aborted."

Both IE and Safari (including iOS) block third party cookies by default. Firefox was apparently going to start blocking all third party cookies from sites the user hasn't visited themselves - http://blog.mozilla.org/privacy/2013/02/25/firefox-getting-smarter-about-third-party-cookies/ - but in Firefox 30 the default is still to accept all cookies.

I found a few possible fixes, but nothing ideal.

It can be fixed in IE by sending a [P3P](http://en.wikipedia.org/wiki/P3P) header, but then ["you're essentially making legally binding claims about how you handle user data"](http://chase-seibert.github.io/blog/2011/06/17/django-csrf-verification-failed-in-ie-iframe.html).

We could disable Django's CSRF protection and check the referer header instead. This would work in (up-to-date) browsers but CSRF attacks would be easier in other applications where users can trigger HTTP requests for each other.  There have also been referer-spoofing bugs in older browsers: http://seclists.org/fulldisclosure/2013/Jul/60. Although, couldn't that be worked around by checking user agents against a list of known-vulnerable browsers? There are a few other problems with this approach listed on the [OWASP CSRF Cheat Sheet](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Checking_The_Referer_Header).

There's also a header called Origin that's designed for this case, but [browser support isn't really there yet](http://www.browserscope.org/?category=security&v=top).

Another idea is to tie the CSRF token to the user's IP instead of to a cookie. For example, you could hash the IP with a secret key and use that as the token.

There are a bunch of workarounds that make pseudo-cookies at http://samy.pl/evercookie/. Using any of those would be a bit of a hack, but the ETag header looks promising.

I had a look at some other online polls to see if they had a solution but they all seemed to have no CSRF protection at all.

**Comment by balajisubr** [comment]
@rupalkhilari Can I work on this next? If not this, please let me know which issue to work on.

**Comment by rupalkhilari** [comment]
@balajisubr , you are welcome to work on this, though I have raised another ticket concerning messages while sharing on social apps, if that seems interesting to you.

**Comment by balajisubr** [comment]
@rupalkhilari Should the CSRF token be disabled for all users except when it is the user who created the poll or the admin of the poll ? I read through the above comments and I am not sure I understand them completely or if they are even relevant any more. @Faxn Do you have any thoughts on this?

**Comment by balajisubr** [comment]
@rupalkhilari I think an approach for this would be to capture the 403 event and then send the user to the login page after which they can login and vote. https://docs.djangoproject.com/en/1.11/ref/csrf/#rejected-requests

But we would need another approach for polls without logins. Did you have any other approaches?
