### ISSUE TITLE
Blog the installation

### ISSUE THREAD

**Issue by jamesonquinn** [electionscience/vote.electionscience.org#19]
This is a good issue for somebody new to the project. All you have to do is install the project and set up a poll... but you have to write it up in a blog post. This will improve both our documentation and our outreach. Also, you'll get to see the poll results on some issue that interests you!

**Comment by souravottawa** [comment]
Hi , Is this issue already been resolved or still we can work on it? thanks

**Comment by ashimaathri** [comment]
Hi @souravottawa. Some basic instructions for linux are in the README.md file but it would be great if we had a wiki page on Github detailing installation on linux as well as windows with screenshots and common pitfalls. This will be of great help to new users.

**Comment by souravottawa** [comment]
Hi , thanks i will start working on it soon.

**Comment by octy40** [comment]
I'd like to work on this as I'm going to setup a new environment and it seems like the easiest issue available. @souravottawa let me know if you already have one already or @rupalkhilari let me know if there's no need for this. Thanks!

**Comment by rupalkhilari** [comment]
@octy40 , Since there hasn't been an update for quite some time, I think we can assume that you can take it up. It is a low priority ticket, but you can always pick it up if it interests you. 
Thanks!
